version: '3.8'

services:
  # APサーバの設定
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
    command: sleep infinity
    network_mode: service:mongo
    environment:
      AZURE_COSMOS_CONNECTIONSTRING: mongodb://root:example@mongo:27017
    
  # DBサーバの設定
  mongo:
    build: 
      context: .
      dockerfile: ./database/Dockerfile
    restart: always
    volumes:
      - ./database:/database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: db_todo
      
  # DB参照GUIツール
  mongo-express:
    image: mongo-express
    restart: always
    # このポート設定を変更するとアクセスできなくなる
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
    depends_on:
      - mongo
